name: github-action-test

#workflow 실행시킬 트리거
on:
    #main branch에 push나 pull request 이벤트 트리거 설정
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        #아래 os 환경에서 실행
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup JAVA
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'

            - name: Grant execute permission for gradlew
              run:
                chmod +x ./Real-BackEnd/gradlew
              shell: bash

            - name: Build with Gradle
              run: 
                cd ./Real-BackEnd
                ./gradlew build
              shell: bash

